spring:
  main:
    web-environment: true
    show-banner: true
  datasource:
    drivername: com.mysql.cj.jdbc.Driver 
    url: "jdbc:mysql://127.0.0.1:3306/model_service?autoReconnect=true"
    username: "aa_user"
    maximum-pool-size: 8
    minimum-idle: 0
  jpa:
    openInView: true
    database: MYSQL
    show-sql: false
    generate-ddl: false
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

endpoints:
  health:
    sensitive: false

management:
  context-path: "/admin"

server:
  port: 8080